name: "Mon blog-notes à moi que j'ai"
description: "Blog personnel d'un sysadmin, tendance hacker"
meta_description: "Blog personnel de Jean Baptiste Favre."
logo: images/me.jpg
url: http://blog.jbfavre.org
domain: blog.jbfavre.org
baseurl: "/"

timezone: Europe/Paris

highlighter: false

paginate: 15
paginate_path: /page:num
paginate_per_category: true

tag_page_dir: tag
tag_feed_dir: tag
category_page_dir: category
category_feed_dir: category

author:
  name: Jean Baptiste Favre
  bio: |
    Sysadmin, tendance hacker.<br/>Ops lead chez BlaBlaCar le jour, moine copiste du numérique la nuit.
  email: webmaster@jbfavre.org

github: jbfavre
twitter: jbfavre

owner:
  name: Jean Baptiste Favre
  url: /cv
  email: webmaster@jbfavre.org
  github: jbfavre
  twitter: jbfavre
  gnusocial: status.jbfavre.org

permalink: /:year/:month/:day/:title

exclude: ["LICENSE.txt", "README.md", "Gemfile", "Gemfile.lock", ".git", ".gitignore", ".bundle", "vendors"]

defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: post
      lang: en
  -
    scope:
      path: _drafts/en
    values:
      layout: post
      lang: en
  -
    scope:
      path: _posts/fr
    values:
      layout: post
      lang: fr
  -
    scope:
      path: _drafts/fr
    values:
      layout: post
      lang: fr
