name: Mon blog-notes à moi que j'ai
description: Le meilleur du pire de mes flux RSS (et de Twitter)
meta_description: "Your New Jekyll Site, Blogging about stuffs"
logo: images/me.jpg
baseurl: "/"
domain: blog.jbfav.re

timezone: Europe/Paris

markdown: redcarpet
highlighter: false
logo: false
paginate: 15


# Details for the RSS feed generator
url:            'http://blog.jbfav.re/'
author:         'Jean-Baptiste Favre'

github: jbfavre
twitter: jbfavre

#owner:
#  name: Jean Baptiste Favre
#  url: /cv
#  position: Network &amp; System Architect
#  company: BlaBlaCar
#  email: webmaster@jbfavre.org
#  github: jbfavre
#  twitter: jbfavre
#  gnusocial: status.jbfavre.org

permalink: /:year/:month/:day/:title
#excerpt_separator: "<!-- -->"
