name: Mon blog-notes à moi que j'ai
description: Le meilleur du pire de mes flux RSS (et de Twitter)
meta_description: "Personal blog of a devops sysadmin"
logo: images/me.jpg
baseurl: "/"
domain: blog.jbfav.re

timezone: Europe/Paris

highlighter: false
paginate: 15
paginate_path: "/page:num"
paginate_per_category: true


# Details for the RSS feed generator
url:            'blog.jbfav.re'
author:
  fullname: 'Jean-Baptiste Favre'
  bio: 'System architect at BlaBlaCar'

github: jbfavre
twitter: jbfavre

#owner:
#  name: Jean Baptiste Favre
#  url: /cv
#  position: Network &amp; System Architect
#  company: BlaBlaCar
#  email: webmaster@jbfavre.org
#  github: jbfavre
#  twitter: jbfavre
#  gnusocial: status.jbfavre.org

permalink: /:year/:month/:day/:title
#excerpt_separator: "<!-- -->"
